apiVersion: v1 
kind: Service
metadata: 
  name: mongodb
  namespace: safety
spec:
  type: {{ .Values.service.type}}
  selector: 
    project: safety
    component: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017 ## services port
      targetPort: 27017 ## container port